# Generated by Django 3.2.4 on 2021-06-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(default='', max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(default=0, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default='', max_length=128, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(default='', max_length=6, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
