# Generated by Django 3.2.4 on 2021-06-16 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210615_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintura',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuarios', verbose_name='Id'),
        ),
    ]
