# Generated by Django 3.2.4 on 2021-06-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pintura_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('email', models.EmailField(max_length=254, null=True, primary_key=True, serialize=False, verbose_name='email')),
                ('titulo', models.CharField(max_length=128, null=True, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='descripcion')),
            ],
        ),
    ]
