# Generated by Django 3.2.4 on 2021-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pintura_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintura',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
