# Generated by Django 3.1 on 2021-07-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pintura_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintura',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pinturas', verbose_name='imagen'),
        ),
    ]
